### ISSUE TITLE
Add "Create Surrogate Key" function

### ISSUE THREAD

**Issue by sean-conkie** [sean-conkie/config-creator#92]
**Detailed Description**
Add a function to the Source to Target to create a surrogate key, where user selects composite key fields and tool creates a hash from them.

**Related Feature(s)**

#47

**Comment by sean-conkie** [comment]
add function with [Button with Dropdown](https://getbootstrap.com/docs/5.0/components/button-group/#nesting)

**Comment by sean-conkie** [comment]
Example css
```css
btn-group-dropdown {background: #fff;}

btn-group-dropdown {
    background-color: #fff;
}

btn-group-left {
    border-radius: 3rem 0rem 0rem 3rem;
}

btn-group-right {
    border-radius: 0rem 3rem 3rem 0rem;
}
```
example html
```html
<div class="btn-group" role="group" aria-label="Button group with nested dropdown">
  <button class="btn-group-left btn-primary" id="id_add_column_button" type="button" style="
    border-radius: 3rem 0rem 0rem 3rem;
"><i class="bi bi-plus"></i> Add Column</button>

  <div class="btn-group" role="group">
    <button id="btnGroupDrop1" type="button" class="btn-group-dropdown btn-group-right btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"></button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1" style="">
      
      <li>
          <a>
              Copy Table
          </a>
      </li>
    </ul>
  </div>
</div>
```
